import torch

x = torch.arange(12)
print(x.device)
print(x)
print(x.shape)
print(x.numel())
print(type(x.shape))
x = x.reshape(3, 4)
print(x)
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))
print(torch.tensor([1, 2, 3]))
print(torch.tensor([[1, 2, 3], [4, 5, 6]]))
x = torch.tensor([1.0, 2, 4, 8])
print(x)
y = torch.tensor([2, 2, 2, 1])
print(y)
print(x + y, x - y, x * y, x / y, x ** y)
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(x)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))
print(x == y)
print(x.sum())